### ISSUE TITLE
Age and Gender

### ISSUE THREAD

**Issue by ghost** [justadudewhohacks/face-api.js-models#1]
Please add age and gender models and weights?

From here - https://github.com/justadudewhohacks/face-api.js/tree/master/weights

**Comment by NicksonYap** [comment]
Hi, @justadudewhohacks 

I'm using face-api.js on Cordova and was successful to make it work by manually loading uncompressed weights

Please upload uncompessed weights for Age and Gender too :D

Thanks!

**Comment by aidlearning** [comment]
can use the uncompessed weight for python?

**Comment by justadudewhohacks** [comment]
Sorry for the delay, uploaded the weights now.
